[[redirects]]
  from = "https://skateakademia.pl"
  to = "https://akademiaskateboardingu.pl"
  status = 301
  force = true

[[redirects]]
  from = "https://dancing-froyo-48645b.netlify.app"
  to = "https://akademiaskateboardingu.pl"
  status = 301
  force = true
